### ISSUE TITLE
Compilation error of cuda/setup.py on windows

### ISSUE THREAD

**Issue by Xieyuan0018** [pytorch/extension-cpp#37]
Hi, I tried to build the extension using your sc. I managed to build from cpp/setup.py and was able to import it. However, I just cannot build from cuda/setup.py. I tried the solution mentioned in other posts i.e. fmax to ::fmax, casting etc, none of them worked.

The error message:
E:/Miniconda/envs/pointnetpy/lib/site-packages/torch/include\torch/csrc/jit/argument_spec.h(161): error: member "torch::jit::ArgumentSpecCreator::DEPTH_LIMIT" may not be initialized
1 error detected in the compilation of "C:/Users/XIEYUA~1/AppData/Local/Temp/tmpxft_00002f00_00000000-10_lltm_cuda_kernel.cpp1.ii".
error: command 'C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v10.1\\bin\\nvcc.exe' failed with exit status 1

- OS: Windows10 Enterprise Version1809
- PyTorch version: 
- How you installed PyTorch (conda, pip, source): conda
- Python version: 1.1.0
- CUDA/cuDNN version: 10.1
- GPU models and configuration: GTX 1080Ti
- GCC version (if compiling from source): N.A.

Any thoughts or suggestions would be greatly appreciated!

**Comment by huoshuaiUSTC** [comment]
I also encountered this problem. How did you solve it?

**Comment by RaphaelRoyerRivard** [comment]
I also get the error with jit and CUDA v10.0 when running `/cuda/setup.py`.
I'd very much like to know the solution to this problem.

**Comment by wantsjean** [comment]
I've "solved" the problem 
when I seach the whole torch folder, it shows that there's only one DEPTH_LIMIT, so I just comment the (161) line where error raised in `...torch/include\torch/csrc/jit/argument_spec.h`
and when I compiled it again, it shows another error:
`<env_lib_dir>\site-packages\torch\lib\include\pybind11\cast.h(1393): error: expression must be a pointer to a complete object type`
then I followed someone's solution 
go straight into the cast.h file and make the following changes
replace `explicit operator type&() { return *(this->value); }`with
`explicit operator type& () { *((type*)(this->value)); }`
and it finally worked.

**Comment by elnazsn1988** [comment]
@Xieyuan0018 @wantsjean Hi, Im encountering the same file compilation error 1 error detected in the compilation of "C:/Users/XIEYUA~1/AppData/Local/Temp/tmpxft_00002f00_00000000-10_lltm_cuda_kernel.cpp1.ii".
error: command 'C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\bin\nvcc.exe' failed with exit status 1 , minus the first part - my error doesnt point me to the Depth variable, although I did fix it just in case and tried another clone version of detectron2 : https://github.com/facebookresearch/detectron2/issues/9 . Can I ask if you guys have used Conda or straight python? I use Admin VS 2019 tools command prompt which initializes correctly, and when testing my nvcc build, it seems to be ok. Am trying Conda now but am wondering if I can isolate the issue and not depend on conda?

**Comment by jamesr66a** [comment]
This should be fixed now by https://github.com/pytorch/pytorch/pull/33002

**Comment by mdcramer** [comment]
I have Pytorch 1.4.0 installed, and have updated everything else, and I'm still getting `torch/csrc/jit/argument_spec.h(190): error: member "torch::jit::ArgumentSpecCreator::DEPTH_LIMIT" may not be initialized`.

**Comment by jamesr66a** [comment]
@mdcramer the fix was landed after the 1.4.0 branch was cut. It will be present in either the nightly build or the 1.5.0 release, when that happens

**Comment by Anandsrivastava90** [comment]
Hi 
      I am intalling Detectron2 in Windows10 , when I run python setup.py install   I am getting this error .Please help me out 

Microsoft Visual Studio 2019
pytorch 1.5
cuda 10.1

Traceback (most recent call last):
  File "D:\anaconda\envs\detectron_project\lib\site-packages\torch\utils\cpp_extension.py", line 1400, in _run_ninja_build
    check=True)
  File "D:\anaconda\envs\detectron_project\lib\subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 115, in <module>
    cmdclass={"build_ext": torch.utils.cpp_extension.BuildExtension},
  File "D:\anaconda\envs\detectron_project\lib\site-packages\setuptools\__init__.py", line 165, in setup
    return distutils.core.setup(**attrs)
  File "D:\anaconda\envs\detectron_project\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "D:\anaconda\envs\detectron_project\lib\distutils\dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "D:\anaconda\envs\detectron_project\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "D:\anaconda\envs\detectron_project\lib\site-packages\setuptools\command\install.py", line 67, in run
    self.do_egg_install()
  File "D:\anaconda\envs\detectron_project\lib\site-packages\setuptools\command\install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "D:\anaconda\envs\detectron_project\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "D:\anaconda\envs\detectron_project\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "D:\anaconda\envs\detectron_project\lib\site-packages\setuptools\command\bdist_egg.py", line 174, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "D:\anaconda\envs\detectron_project\lib\site-packages\setuptools\command\bdist_egg.py", line 160, in call_command
    self.run_command(cmdname)
  File "D:\anaconda\envs\detectron_project\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "D:\anaconda\envs\detectron_project\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "D:\anaconda\envs\detectron_project\lib\site-packages\setuptools\command\install_lib.py", line 11, in run
    self.build()
  File "D:\anaconda\envs\detectron_project\lib\distutils\command\install_lib.py", line 107, in build
    self.run_command('build_ext')
  File "D:\anaconda\envs\detectron_project\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "D:\anaconda\envs\detectron_project\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "D:\anaconda\envs\detectron_project\lib\site-packages\setuptools\command\build_ext.py", line 87, in run
    _build_ext.run(self)
  File "D:\anaconda\envs\detectron_project\lib\site-packages\Cython\Distutils\old_build_ext.py", line 186, in run
    _build_ext.build_ext.run(self)
  File "D:\anaconda\envs\detectron_project\lib\distutils\command\build_ext.py", line 339, in run
    self.build_extensions()
  File "D:\anaconda\envs\detectron_project\lib\site-packages\torch\utils\cpp_extension.py", line 580, in build_extensions
    build_ext.build_extensions(self)
  File "D:\anaconda\envs\detectron_project\lib\site-packages\Cython\Distutils\old_build_ext.py", line 195, in build_extensions
    _build_ext.build_ext.build_extensions(self)
  File "D:\anaconda\envs\detectron_project\lib\distutils\command\build_ext.py", line 448, in build_extensions
    self._build_extensions_serial()
  File "D:\anaconda\envs\detectron_project\lib\distutils\command\build_ext.py", line 473, in _build_extensions_serial
    self.build_extension(ext)
  File "D:\anaconda\envs\detectron_project\lib\site-packages\setuptools\command\build_ext.py", line 208, in build_extension
    _build_ext.build_extension(self, ext)
  File "D:\anaconda\envs\detectron_project\lib\distutils\command\build_ext.py", line 533, in build_extension
    depends=ext.depends)
  File "D:\anaconda\envs\detectron_project\lib\site-packages\torch\utils\cpp_extension.py", line 562, in win_wrap_ninja_compile
    with_cuda=with_cuda)
  File "D:\anaconda\envs\detectron_project\lib\site-packages\torch\utils\cpp_extension.py", line 1140, in _write_ninja_file_and_compile_objects
    error_prefix='Error compiling objects for extension')
  File "D:\anaconda\envs\detectron_project\lib\site-packages\torch\utils\cpp_extension.py", line 1413, in _run_ninja_build
    raise RuntimeError(message)
RuntimeError: Error compiling objects for extension

**Comment by tehreemnaqvi** [comment]
I got the same error.

I tried a lot to fix this but couldn't debug the errors.

How to fix this error?

Please help!!

Thanks
